### ISSUE TITLE
Webcam not working in macos monterey

### ISSUE THREAD

**Issue by nleclerc** [piwebcam/PiWebcam#47]
I just upgraded to monterey (12.0.1) and the piwebcam is listed in usb devices but is not available in any program (photo booth, chrome or obs).
It worked perfectly with previous macos version, big sur 11.6.1.

**Comment by davide-bertola-deltatre** [comment]
Bummer.
Happens to many external cameras based on mjpeg codec
https://www.reddit.com/r/MacOSBeta/comments/p79rq6/monterey_beta_5_external_usb_camera_doesnt_work/

**Comment by davibe** [comment]
Bummer.
Happens to many external cameras based on mjpeg codec
https://www.reddit.com/r/MacOSBeta/comments/p79rq6/monterey_beta_5_external_usb_camera_doesnt_work/

**Comment by nleclerc** [comment]
I'm not sure it's the same issue because in my case the camera isn't even listed in applications. I can't even get to the point of not getting a picture or waiting for the cam to initialize.

**Comment by user2684** [comment]
Hi guys, not sure I got the issue. PiWebcam is exposing a web interface through which you can access the camera, not sure I've understood what USB is used for in your scenario. Many thanks!

**Comment by nleclerc** [comment]
> With PiWebcam you can turn a Raspberry Pi into a fully-featured, dummy-proof Webcam with just one click.

i'm using the piwebcam as an actual usb webcam on my system, just as the project states it does.
Works fine on windows and macos prior to monterey.

**Comment by jknutson** [comment]
FWIW, I experienced an issue with my Pi based USB Webcam after the Monterey upgrade, though it is **not** running "piwebcam" software, despite showing up to my mac with "piwebcam" as the name.

The software I am running is https://github.com/showmewebcam/showmewebcam

**Comment by user2684** [comment]
Guys apologize but I'm really missing something here. https://github.com/showmewebcam/showmewebcam is a completely different project and unrelated to PiWerbcam. PiWerbcam has nothing to do with USB; PiWerbcam connects to the WIFI and expose a web service there. There is no other way to interfact with it. What am I missing?

**Comment by jknutson** [comment]
> Guys apologize but I'm really missing something here. https://github.com/showmewebcam/showmewebcam is a completely different project and unrelated to PiWerbcam. PiWerbcam has nothing to do with USB; PiWerbcam connects to the WIFI and expose a web service there. There is no other way to interfact with it. What am I missing?

I should have been more clear, I am using a different bit of software, I only mentioned it because the device shows up as "Piwebcam" to my Mac, so perhaps that is why some others are finding this project, when they really are looking for somethingelse.

@nleclerc is there any chance that you are actually using this software to run your USB camera: https://github.com/showmewebcam/showmewebcam ? If you are, it appears that there is a fix for Monterey now: https://github.com/showmewebcam/showmewebcam/issues/164

**Comment by user2684** [comment]
oooh now I get it :-) Thanks for the clarification. I'm going to close this issue then since unrelated to PiWebcam but feel free to carry on the discussion here if you like

**Comment by nleclerc** [comment]
I think you're right @jknutson, i was probably using that project.
Thanks a lot and sorry for the confusion 😅

**Comment by jknutson** [comment]
I may look into opening an issue/PR on the other project to rename the device; it caused me some confusion as well.

I am glad I found this software, though. I will likely use it for a trail camera in addition to my showmewebcam based USB camera.
